[package]
authors = ["Johan Helsing <johanhelsing@gmail.com>"]
categories = ["game-development"]
description = "A camera that allows panning by dragging with the mouse"
edition = "2021"
keywords = ["gamedev", "bevy"]
license = "MIT OR Apache-2.0"
name = "bevy_pancam"
readme = "readme.md"
repository = "https://github.com/johanhelsing/bevy_pancam"
version = "0.4.0"

[dependencies]
bevy = {git = "https://github.com/bevyengine/bevy", branch = "main", features = ["render"], default-features = false}

[dev-dependencies]
bevy = {git = "https://github.com/bevyengine/bevy", branch = "main", default-features = false, features = [
  "render",
  "bevy_winit",
  "x11", # github actions runners don't have libxkbcommon installed, so can't use wayland
]}
rand = "0.8"
