[package]
name = "bevy_pancam"
version = "0.1.0"
edition = "2018"
license = "MIT OR Apache-2.0"
readme = "readme.md"

[dependencies]

[dependencies.bevy]
version = "0.5"
features = ["render"]
default-features = false

[dev-dependencies]
rand = "0.8"

[dev-dependencies.bevy]
version = "0.5"
