[package]
name = "bevy_pancam"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
readme = "readme.md"

[dependencies]
bevy = { version = "0.6",  features = ["render"], default-features = false }

[dev-dependencies]
bevy = { version = "0.6", features = ["render"] }
rand = "0.8"
